name: plant_log
description: The Flutter project for Plant Log.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  flutter_riverpod: ^2.3.6
  http: ^1.1.0
  hooks_riverpod: ^2.3.7
  cached_network_image: ^3.3.1
#  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.6
  flutter_lints: ^4.0.0
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
