name: plant_log
description: The Flutter project for Plant Log.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  equatable: ^2.0.5
  json_annotation: ^4.9.0
  flutter_riverpod: ^2.5.1
  http: ^1.2.1
  hooks_riverpod: ^2.5.1
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  firebase_storage: ^12.0.0
  cached_network_image: ^3.3.1
  path_provider: ^2.1.3
  google_sign_in: ^6.2.1
  flutter_signin_button: ^2.0.0
  photo_manager: ^3.1.1
  flutter_debouncer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.10
  flutter_lints: ^4.0.0
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
